"""change uuid to string

Revision ID: 7d04266b9d57
Revises: 660432a2c032
Create Date: 2025-05-14 14:27:07.301553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d04266b9d57'
down_revision = '660432a2c032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_references', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_references', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.String(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
